baseURL = "https://donderom.com/"
languageCode = "en-us"
title = "Roman Parykin"
theme = "blue-square"

disableKinds = ["section", "taxonomy", "term"]
disableHugoGeneratorInject = true

[params]
  subtitle = "Software development, distributed systems, &amp; natural language processing"
  banner = "banner.png"

[taxonomies]
  feature = "features"

[markup]
  # https://gohugo.io/configuration/markup/#extras
  [markup.goldmark]
    [markup.goldmark.extensions]
      strikethrough = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = true
        [markup.goldmark.extensions.extras.insert]
          enable = true
        [markup.goldmark.extensions.extras.mark]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = false
        [markup.goldmark.extensions.extras.superscript]
          enable = false
  [markup.highlight]
    noClasses = false

[minify]
  disableSVG = true
  disableXML = true

[services]
  [services.rss]
    limit = 10
